### ISSUE TITLE
Nested Dragdealers

### ISSUE THREAD

**Issue by TamMcDonald** [skidding/dragdealer#88]
I've got two dragdealers, one nested inside the other. The issue I'm having is that the parent dragdealer (restricted to vertical only) works fine, while the child (horizontal only) bugs out.

Is there a way to fix this or work around it, or is Dragdealer inception impossible?

**Comment by skidding** [comment]
Hi @TamMcDonald,

Dragdealer does not support nested instances, so you'll probably need to find something else to accomplish this, or tweak it at your own expense.

I did, however, work on a different version of Dragdealer to support this, but it got abandoned a long long time ago because I didn't have the time nor the drive to complete it. There's an interesting paragraph about this in my [latest post on Dragdealer.](https://medium.com/@skidding/your-local-dragdealer-became-more-trustworthy-370ff43bcb31)

> Yet I never got around to release a major update. Surely with the skills acquired in all this time I could write a far better version—I kept thinking, without ever completing the rewrite attempts. One was quite good, it supported infinite levels of drag components inside drag components, with a bubbling mechanism for drag events and sliding transitions to transfer from child margins to parents. But did anybody request this? No. That’s why it would never see the light of day, because solving an imaginary problem takes forever.

At least you validated the need I was trying to fix (a few years later) :-)

Good luck!
