### ISSUE TITLE
Cleaning the instance

### ISSUE THREAD

**Issue by ayamflow** [skidding/dragdealer#89]
Hey there!
I noticed the API doesn't explain how to properly clean the Dragdealer instance, for instance on a SPA you might want to be sure that no listener/rAF loop/... is still running,

I'm currently doing the following:
```js
this.slider.disable();
this.slider.unbindEventListeners();
```

But I'm not sure if it's enough?

**Comment by skidding** [comment]
`this.slide.disable` is not needed in this case, unbinding the listeners does it.

No need to worry about the rAF loop because it doesn't work like setInterval, but rather like setTimeout (which is the fallback) and is set on every loop. So [canceling the current loop](https://github.com/skidding/dragdealer/blob/master/src/dragdealer.js#L397) makes sure [a new one](https://github.com/skidding/dragdealer/blob/master/src/dragdealer.js#L602) isn't registered anymore.

**Comment by ayamflow** [comment]
Great, so `unbindEventListeners()` is the way to go then!
